[package]
name = "imres"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24.5"
walkdir = "2"
indicatif = "0.17.2"
rayon = "1.7"

